site:
  title: Belief and Reason
  url: /
  start_page: intro-index::index.adoc
  robots: allow

# Output directory and tmp cache
output:
  dir: ./public
runtime:
  cache_dir: ./.cache/antora
  # Set log level
  log:
    level: debug

# List of common words and terms. For example: Use {br} within documents for replacement
# Asciidoc syntactical sugar functions
asciidoc:
  attributes:
    br: "Belief and Reason"

    linkattrs: true # Allows link text, optional target and roles as attributes on links
    sectlinks: true # Turns section titles into links
    sectnums: true # Turns on section numbers
    sectnumlevels: 5 # Number of section levels allowed
    toclevels: 3 # Number of tables of content levels allowed
    toc: center # Table of contents at top of document
    icons: font # Enables font icons
    experimental: true # Enables button, menu and keyboard macros
    idprefix: "" # Custom id prefix
    idseparator: "-" # Custom id separator
    page-pagination: "" # Custom pagination

# Topic source repository listing - all documents stored on github
content:
  sources:
  # Intro
    - url: https://github.com/beliefandreason-admin/br-intro.git
      branches: main
      start_path: research
  # Archeology
    - url: https://github.com/beliefandreason-admin/br-archeology.git
      branches: main
  # Astronomy
    - url: https://github.com/beliefandreason-admin/br-astronomy.git
      branches: main
  # Bible
    - url: https://github.com/beliefandreason-admin/br-bible.git
      branches: main
  # Biology
    - url: https://github.com/beliefandreason-admin/br-biology.git
      branches: main
  # Chemistry
    - url: https://github.com/beliefandreason-admin/br-chemistry.git
      branches: main
  # Creation
    - url: https://github.com/beliefandreason-admin/br-creation.git
      branches: main
  # Daily Devotions
    - url: https://github.com/beliefandreason-admin/br-devotions.git
      branches: main
  # Dinosaurs
    - url: https://github.com/beliefandreason-admin/br-dinosaurs.git
      branches: main
  # Evolution
    - url: https://github.com/beliefandreason-admin/br-evolution.git
      branches: main
  # Geology
    - url: https://github.com/beliefandreason-admin/br-geology.git
      branches: main
  # History
    - url: https://github.com/beliefandreason-admin/br-history.git
      branches: main
  
  # Information Science
    - url: https://github.com/beliefandreason-admin/br-information-science.git
      branches: main
  
  # Mathematics
    - url: https://github.com/beliefandreason-admin/br-mathematics.git
      branches: main
  
  # Philosophy
    - url: https://github.com/beliefandreason-admin/br-philosophy.git
      branches: main
  
  # Theology
  #  - url: https://github.com/beliefandreason-admin/br-theology.git
  #    branches: main

# User Interface Configuration
ui:
  bundle:
    # Default Base User Interface
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  # Custom styling for User Interface
  supplemental_files: ./branding/supplemental-ui

antora:
  extensions:
  - '@antora/lunr-extension'